version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth -H unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.theomarty.fr`)"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
volumes:
  portainer_data:

networks:
  web:
    external: true