version: '3'

services:
  nextcloud:
      image: nextcloud
      container_name: nextcloud
      env_file: .env
      environment:
        - MYSQL_DATABASE=nextcloud
      restart: always
      volumes:
        - ./nextcloud:/var/www/html
        - ./nextcloud/apps:/var/www/html/custom_apps
        - ./nextcloud/data:/var/www/html/data
        - ./nextcloud/config:/var/www/html/config
      labels:
        - "traefik.frontend.rule=Host:cloud.theomarty.fr"
      networks:
        - web
      depends_on:
        - mysql
networks:
  web:
    external: true
