version: '3'

services:
  hugo:
    container_name: hugo
    image: nithwith/hugo_blog
    labels:
      - "traefik.frontend.rule=Host:theomarty.fr"
    ports:
      - "1313:1313"
    networks:
      - web
networks:
  web:
    external: true
