version: '3'

services:
  hugo:
    container_name: hugo
    build: ./hugo
    labels:
      - "traefik.frontend.rule=Host:theomarty.fr"
    ports:
      - "1313:80"
    networks:
      - web
networks:
  web:
    external: true
