version: '3'

services:
  traefik:
    image: traefik:1.7
    command: --docker --docker.domain=hakase-labs.io
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.frontend.rule=Host:$PROXY_DOMAIN"
      - "traefik.port=8080"
    restart: always
    environment:
      - LEXICON_SLEEP_TIME=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme.json
    container_name: traefik
    restart: always
    networks:
      - web
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.frontend.rule=Host:portainer.theomarty.fr"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.entryPoints=http,https"
    container_name: portainer
    networks:
      - web
volumes:
  portainer_data:

networks:
  web:
    external: true

