defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[docker]
domain = "theomarty.fr"
watch = true
network = "web"

[acme]
email = "contact@theomarty.fr"
storage = "acme.json"
caServer = "https://acme-v01.api.letsencrypt.org/directory"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
